---
title: "GitHub Reposity Star"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    vertical_layout: fill
    source_code: https://github.com/declan-haojin
    favicon: https://cdn.jsdelivr.net/gh/declan-haojin/blog-image@master/img/20200615000056.png
---

```{r setup, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(dplyr)
library(scales)
library(visreg)
library(RColorBrewer)
library(gridExtra)
library(ggthemes)
library(GGally)
library(corrplot)
library(ROCR)
library(caret)
data = read.csv("new.csv")


# data = data[,-1]
# data = data[,-1]
# data = data[,-7]
# data = data[,-7]
# data = data[,-7]
# data = data[,-7]
# data = data[,-11]
# data = data[,-11]
# data = data[,-11]
# data = data[,-7]
# data = data[,-7]
# data = data[,-9]
# data = data[,-9]
# 
# write.csv(data,"new.csv")

# Order by star


# Change "k" into normal number form
for(i in c(1:1500))
{
  for(j in c(5:9))
  {
    len = nchar(data[i,j])
    label = substring(data[i,j], len, len)
    rest = substring(data[i,j], 1, len-1)
    if(identical(label, "k"))
    {
      data[i,j] = as.numeric(rest) * 1000
    }
    else if(len > 3)
    {
      data[i,j] = paste( substring(data[i,j], 1, len-4), substring(data[i,j], len-2,len), sep="")
    }
  }
}

data$star = as.numeric(data$star)
data$fork = as.numeric(data$fork)
data$watch = as.numeric(data$watch)
data$commits = as.numeric(data$commits)
data$branches = as.numeric(data$branches)

typeof(data$star)
summary(data)

data = data[,-1]

data = data[order(data$star, decreasing= T),]

```


Overview {data-icon="fa-list"}
=======================================================================

Inputs {.sidebar}
-----------------------------------------------------------------------

```{r}
numericInput("maxrows", "Recent downloads window:", 50)
```


Row
-----------------------------------------------------------------------

### Data of GitHub
```{r}
valueBox(2020, icon = "fa-calendar-alt", color = "warning")
```

### Repositories

```{r}
valueBox(1500, icon = "fa-dropbox", color = "primary")
```

### Topics

```{r}
valueBox(20, icon = "fa-star", color = "info")
```



Row
-----------------------------------------------------------------------


### ChartA

```{r}
#ggplot(data, aes(y=star,x=name)) + geom_col()
ggpairs(data[,4:8])
```

### ChartB

```{r}
corrplot(cor(data[,4:8]), method = "color") 
```


Row
-----------------------------------------------------------------------

### ChartB

```{r}
ggplot(data,aes(star,watch,color=topic)) + geom_point()+ theme_gdocs()
```

### ChartC

```{r}
p <- ggplot(data,aes(x=topic,y=star,fill=topic))
p + geom_col()
```







Linear Regression {data-icon="fa-list"}
=======================================================================


Inputs {.sidebar}
-----------------------------------------------------------------------

```{r}
numericInput("seed", "Random value for spliting training and test sets", 50000, 0, 99999)
sliderInput("size", "Training/Test set size", 0, 1500, 1300)
```



Column
-----------------------------------------------------------------------

### RMSE Index for Training Set
```{r}
valueBox(0, icon = "fa-star", color = "primary")

# renderValueBox({
#   valueBox(
#     value = rate,
#     icon = "fa-area-chart",
#     color = if (rate >= input$rateThreshold) "warning" else "primary"
#   )
# })
```

### RMSE Index for Test Set
```{r}
valueBox(7, icon = "fa-star", color = "info")
```



Column
-----------------------------------------------------------------------

### Linear Regression

```{r}
set.seed(777)
train_id = sample(nrow(data), size = 0.79*nrow(data))
train_set <- data[train_id,]
test_set <- data[-train_id,]
#print(paste(nrow(train_set), "train +", nrow(test_set), "test"))
model_lm = lm(star ~ fork+watch+commits+branches, train_set)
plot(model_lm)
#summary(model_lm)

train_predict_lm = predict(model_lm, train_set)
test_predict_lm = predict(model_lm, test_set)

sqrt(mean((train_set$star - train_predict_lm)^2))
sqrt(mean((test_set$star - test_predict_lm)^2))
```

Random Forest {data-icon="fa-list"}
=======================================================================

### Random Forest

Row
-----------------------------------------------------------------------

### RMSE Index for Training Set
```{r}
valueBox(0, icon = "fa-star", color = "primary")
```

### RMSE Index for Test Set
```{r}
valueBox(7, icon = "fa-star", color = "info")
```

Row
-----------------------------------------------------------------------

### Error
```{r}
library(randomForest)
model_rf = randomForest(star ~ fork+watch+commits+branches, data)
plot(model_rf)
```


### Visualization Pairs (4 variables) 
```{r}
par(mfrow = c(2, 2))  ##四个变量一起看
visreg(model_rf)
```

```{r}
train_predict_rf = predict(model_rf, train_set)
test_predict_rf = predict(model_rf, test_set)

sqrt(mean((train_set$star - train_predict_rf)^2))
sqrt(mean((test_set$star - test_predict_rf)^2))
```




SVM {data-icon="fa-list"}
=======================================================================


Row
-----------------------------------------------------------------------

### Visualization Pairs (4 variables)

```{r}
library(e1071)
model_svm = svm(star ~ fork+watch+commits+branches, data, cost = 1000, gamma = 0.0001)
# summary(model_svm)


train_predict_svm = predict(model_svm, train_set)
test_predict_svm = predict(model_svm, test_set)

par(mfrow = c(2, 2))  ##四个变量一起看
visreg(model_svm)
```

### Two Variables
```{r}
visreg(model_svm, "star", gg = TRUE, ylab = "watch")#单个变量

sqrt(mean((train_set$star - train_predict_svm)^2))
sqrt(mean((test_set$star - test_predict_svm)^2))
```



Conclusion {data-icon="fa-list"}
=======================================================================

Data {data-icon="fa-list"}
=======================================================================
```{r}
DT::datatable(data, options = list(pageLength = 25))
```
```

